//! Release-published starter scaffold (doc-10, TASK-74).
//!
//! The starter repository is a *consumer artifact*, not a second implementation of
//! pixi-sandbox: every file it owns is either generated by one published release of the CLI
//! or rendered here from that same release's tag. This module holds the half the CLI does not
//! generate — the Pixi project itself, the ignore file and the README — plus the validation
//! that the assembled tree really is pinned to one release.
//!
//! Why Rust and not the workflow: `consumer-proof.yml` already proves this recipe works, but
//! it spends ~60 lines of `run:` shell carrying `# multiline-run-allowed:` opt-outs to do it.
//! The repository's rule is that a workflow step is an action or a one-line task (task-36), so
//! the starter lane keeps its logic here where it is typed, unit-tested against tempdirs, and
//! shared by every runner instead of duplicated per shell dialect.

use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};

/// Files the starter owns that `pixi-sandbox init` does not write.
///
/// `init` owns the publisher, the relock workflow and the restore launcher, and writes a
/// default `pixi-sandbox.toml` once. Everything below is the Pixi project that gives those
/// files something to pack.
pub const SCAFFOLD_FILES: [&str; 3] = ["pixi.toml", ".gitignore", "README.md"];

/// Every file a validated starter revision must contain before it is published.
pub const REQUIRED_FILES: [&str; 7] = [
    "pixi.toml",
    "pixi.lock",
    "pixi-sandbox.toml",
    ".gitignore",
    "README.md",
    ".github/workflows/publish-sandbox.yml",
    ".github/workflows/relock.yml",
];

/// Paths that must never be committed to the starter: runtime state, caches and anything
/// that could carry a credential (doc-10 "Credentials and safety").
pub const FORBIDDEN_PATHS: [&str; 6] = [
    ".pixi",
    ".pixi-sandbox",
    ".env",
    "SHA256SUMS",
    "pixi-sandbox",
    "pixi-sandbox.exe",
];

/// Strip a leading `v` so a tag and a CLI version can be compared.
///
/// The release tag is `v1.2.3`; the generated publisher stamps the bare `1.2.3`. Comparing
/// them is the whole point of [`verify`], so the two spellings are normalised in one place.
#[must_use]
pub fn version_of(tag: &str) -> &str {
    tag.strip_prefix('v').unwrap_or(tag)
}

/// The starter's Pixi project.
///
/// Deliberately language-neutral (doc-10 "Template ownership and contents"): it supplies the
/// Pixi/Sandbox scaffold and one documented development task, not a framework starter. The
/// single dependency is not decoration — a dependency-free environment solves to no
/// platform-specific lock entry at all, and `pixi-pack` then fails with "platform not found in
/// lockfile: linux-64". `consumer-proof.yml` hit exactly that and picked `ripgrep` for the same
/// reason; keeping the same choice keeps the two lanes comparable.
#[must_use]
pub fn render_pixi_toml(name: &str) -> String {
    format!(
        "# Pixi project for the pixi-sandbox starter. Replace this with your own project:\n\
         # the only parts Pixi Sandbox needs are a workspace with at least one real dependency\n\
         # and a platform that matches the `[[bundle]]` in pixi-sandbox.toml.\n\
         [workspace]\n\
         name = \"{name}\"\n\
         channels = [\"https://prefix.dev/conda-forge\"]\n\
         platforms = [\"linux-64\"]\n\
         \n\
         [dependencies]\n\
         # One small, fast-to-fetch package keeps the environment real. A dependency-free\n\
         # workspace produces a lockfile with no per-platform data, which packs into a\n\
         # transport that cannot be restored.\n\
         ripgrep = \"*\"\n\
         \n\
         [tasks]\n\
         # The documented development command. `pixi run dev` is what the README tells a new\n\
         # user to run, and what CI runs to prove a fresh clone works.\n\
         dev = \"rg --version\"\n"
    )
}

/// The starter's ignore file.
///
/// `.pixi/` and `.pixi-sandbox/` are restored runtime state, not sources. Committing either
/// would ship a stale environment to everyone who uses the template.
#[must_use]
pub fn render_gitignore() -> String {
    "# Pixi's installed environments: restored from pixi.lock, never committed.\n\
     .pixi/\n\
     \n\
     # Pixi Sandbox runtime state: transports, vendored crates and downloaded tools.\n\
     .pixi-sandbox/\n\
     \n\
     # A downloaded standalone binary and its checksum manifest are build inputs, not sources.\n\
     /pixi-sandbox\n\
     /pixi-sandbox.exe\n\
     /SHA256SUMS\n"
        .to_string()
}

/// The starter README.
///
/// doc-10 requires the prose to state the release it corresponds to and to cross-link the main
/// project, so a user can tell exactly which pixi-sandbox created their scaffold.
#[must_use]
pub fn render_readme(
    tag: &str,
    source_commit: &str,
    source_repo: &str,
    starter_repo: &str,
) -> String {
    let version = version_of(tag);
    format!(
        "# pixi-sandbox starter\n\
         \n\
         A ready-to-run [Pixi](https://pixi.sh) project with\n\
         [Pixi Sandbox]({server}/{source_repo}) already configured. Everything in this\n\
         repository is generated from one published release — there is no setup step.\n\
         \n\
         | | |\n\
         |---|---|\n\
         | pixi-sandbox release | [`{tag}`]({server}/{source_repo}/releases/tag/{tag}) |\n\
         | source commit | [`{short}`]({server}/{source_repo}/commit/{source_commit}) |\n\
         | starter repository | [{starter_repo}]({server}/{starter_repo}) |\n\
         \n\
         ## Use it\n\
         \n\
         1. Press **Use this template** and create a repository under your own owner.\n\
         2. Clone it and run the development task:\n\
         \n\
         ```sh\n\
         pixi run dev\n\
         ```\n\
         \n\
         3. Push to `main`. The included publisher packs your locked environment and pushes a\n\
            self-contained sandbox branch, using your repository's own `GITHUB_TOKEN`.\n\
         \n\
         No `pixi-sandbox init`, no workflow copying, no version to choose, and no token owned\n\
         by anyone else.\n\
         \n\
         ## What is generated\n\
         \n\
         These files are owned by pixi-sandbox `{version}` and are regenerated by\n\
         `pixi-sandbox init`. Edit them only if you are ready to own them:\n\
         \n\
         - `.github/workflows/publish-sandbox.yml` — packs and publishes the sandbox branch\n\
         - `.github/workflows/relock.yml` — refreshes `pixi.lock` on pull requests\n\
         - `restore.sh` — offline restore launcher for an airlocked host\n\
         - `pixi-sandbox.toml` — the reviewed publish plan; written once, then yours\n\
         \n\
         `pixi.toml`, `pixi.lock`, `.gitignore` and this README are yours from the start.\n\
         \n\
         ## Updating\n\
         \n\
         This repository is a snapshot of `{tag}`. A newer pixi-sandbox release produces a new\n\
         starter revision; it does not change repositories already created from this template.\n\
         Your own repository upgrades itself through the weekly upgrade lane in the publisher\n\
         workflow, which opens a reviewable pull request.\n",
        server = "https://github.com",
        short = &source_commit[..source_commit.len().min(7)],
    )
}

/// Write the three scaffold files into `out`.
///
/// Idempotent by construction: every byte is derived from the arguments, so a second call with
/// the same inputs produces the same tree. That is what makes the publication contract's
/// "rerunning the same verified tag produces no content change" testable.
///
/// # Errors
///
/// Fails when `tag` is not a strict semver tag, when `source_commit` is not a hex SHA of at least seven characters, or when a file cannot be written.
pub fn scaffold(
    out: &Path,
    name: &str,
    tag: &str,
    source_commit: &str,
    source_repo: &str,
    starter_repo: &str,
) -> Result<()> {
    if !is_strict_tag(tag) {
        bail!("starter tag must be a strict semver tag like v1.2.3, got {tag:?}");
    }
    if source_commit.len() < 7 || !source_commit.chars().all(|c| c.is_ascii_hexdigit()) {
        bail!("starter source commit must be a hex sha of at least 7 chars, got {source_commit:?}");
    }
    std::fs::create_dir_all(out).with_context(|| format!("creating {}", out.display()))?;
    // Keyed by SCAFFOLD_FILES so the published set and the written set cannot drift apart.
    let contents = [
        render_pixi_toml(name),
        render_gitignore(),
        render_readme(tag, source_commit, source_repo, starter_repo),
    ];
    for (file, body) in SCAFFOLD_FILES.iter().zip(&contents) {
        crate::util::write_atomic(&out.join(file), body)?;
    }
    println!(
        "scaffolded starter for {tag} in {} ({} files)",
        out.display(),
        SCAFFOLD_FILES.len()
    );
    Ok(())
}

/// `v1.2.3` and nothing looser. A starter revision that cannot name an exact release is not
/// publishable (doc-10 "Validation and evidence" item 1).
fn is_strict_tag(tag: &str) -> bool {
    crate::util::is_strict_semver(version_of(tag))
}

/// The paths the starter's next commit would contain, or `None` when there is no git to ask.
///
/// `None` is a legitimate answer rather than an error: `verify` is pointed at scratch trees by
/// tests and by a developer checking a draft, and neither has a repository. What it must not
/// become is *optimistic* — with no index and no ignore rules in play, the only honest answer
/// is that nothing can be proven absent, so the caller falls back to the existence check.
///
/// A `git` that exists but fails for another reason (a corrupt index, an unreadable work tree)
/// is an error and propagates, because that failure is worth reporting on its own.
fn publishable_paths(dir: &Path) -> Result<Option<Vec<String>>> {
    use pixi_sandbox_git::ShellGit;
    let git = ShellGit::new();
    if !git.is_work_tree(dir)? {
        return Ok(None);
    }
    Ok(Some(git.ls_publishable(dir)?))
}

/// Report every reason `dir` is not a publishable starter revision for `tag`.
///
/// Returns findings rather than failing on the first one, for the same reason
/// `check-repository` does: one run should tell you everything that is wrong (D13).
///
/// The forbidden-path half is judged on *the tree git would commit*, not on the directory
/// listing: the assembly steps leave runtime state behind on purpose, and the starter's
/// `.gitignore` is what makes that harmless. Everything else here is about file contents and
/// is read straight off disk.
///
/// # Errors
///
/// Fails only when git cannot be asked what it would commit. Every content problem is returned as a finding, not as an error.
pub fn verify(dir: &Path, tag: &str) -> Result<Vec<String>> {
    let mut findings = Vec::new();
    if !is_strict_tag(tag) {
        findings.push(format!(
            "tag {tag:?} is not a strict semver tag like v1.2.3"
        ));
        return Ok(findings);
    }
    let version = version_of(tag);

    for required in REQUIRED_FILES {
        if !dir.join(required).exists() {
            findings.push(format!("missing required file {required}"));
        }
    }
    // The verdict is about the revision, not about the directory. The steps that assembled the
    // starter (`pixi lock`, `pixi run dev`) necessarily leave `.pixi/` behind, and the starter's
    // own `.gitignore` is what keeps those bytes out of the commit — so ask git what it would
    // take (task-85 AC#2), and fall back to existence only where there is no work tree to ask.
    let publishable = publishable_paths(dir)?;
    for forbidden in FORBIDDEN_PATHS {
        let present = dir.join(forbidden).exists();
        let git_would_take = match &publishable {
            Some(paths) => {
                let prefix = format!("{forbidden}/");
                paths
                    .iter()
                    .any(|path| path == forbidden || path.starts_with(&prefix))
            }
            None => present,
        };
        if present && git_would_take {
            findings.push(format!(
                "{forbidden} must not be committed to the starter (runtime state or credential)"
            ));
        }
    }

    let workflow_path = dir.join(".github/workflows/publish-sandbox.yml");
    if workflow_path.exists() {
        let workflow = crate::util::read(&workflow_path)?;
        let marker = format!("# pixi-sandbox-version: {version}");
        if !workflow.lines().any(|line| line.trim() == marker) {
            findings.push(format!(
                "publisher does not carry the {marker:?} marker, so it was not generated by {tag}"
            ));
        }
        let env_pin = format!("PIXI_SANDBOX_VERSION: {version}");
        if !workflow.lines().any(|line| line.trim() == env_pin) {
            findings.push(format!("publisher does not pin {env_pin:?}"));
        }
        findings.extend(floating_version_findings(&workflow, "publisher"));
    }

    let readme_path = dir.join("README.md");
    if readme_path.exists() {
        let readme = crate::util::read(&readme_path)?;
        if !readme.contains(tag) {
            findings.push(format!("README does not state the release tag {tag}"));
        }
    }
    Ok(findings)
}

/// Lines that resolve a *version* as `latest` rather than pinning one.
///
/// A blanket search for `latest` is wrong here: `runs-on: ubuntu-latest` is a runner label, not
/// a version resolution, and it appears in every generated workflow. Only the spellings that
/// would actually float a pixi-sandbox version are findings.
#[doc(hidden)] // test boundary (tests/starter.rs)
#[must_use]
pub fn floating_version_findings(text: &str, what: &str) -> Vec<String> {
    const FLOATING: [&str; 4] = ["releases/latest", "==latest", "--version latest", "@latest"];
    crate::util::lines_without_opt_out(text)
        .filter_map(|(number, line)| {
            FLOATING
                .iter()
                .find(|needle| line.contains(**needle))
                .map(|needle| {
                    format!("{what} line {number} resolves a floating version ({needle})")
                })
        })
        .collect()
}

/// Verify a downloaded release asset against the release's own `SHA256SUMS`.
///
/// `gh release download` is HTTPS and authenticated, but doc-10 requires the checksum manifest
/// to be *checked*, not merely present: the starter's whole claim is that it was generated by a
/// specific, verified binary.
///
/// # Errors
///
/// Fails when `sums` has no line for `asset_name`, when the binary cannot be hashed, or when its digest differs from the one in `sums`.
pub fn verify_asset(binary: &Path, sums: &Path, asset_name: &str) -> Result<()> {
    let sums_text = crate::util::read(sums)?;
    let expected = sums_text
        .lines()
        .find_map(|line| {
            let (digest, name) = line.split_once("  ")?;
            (name.trim() == asset_name).then_some(digest.trim())
        })
        .with_context(|| format!("{asset_name} has no line in {}", sums.display()))?;
    let actual = pixi_sandbox_core::shard::sha256_file(binary)
        .with_context(|| format!("hashing {}", binary.display()))?;
    if !actual.eq_ignore_ascii_case(expected) {
        bail!(
            "checksum mismatch for {asset_name}: SHA256SUMS says {expected}, downloaded file is {actual}"
        );
    }
    println!("verified {asset_name} against SHA256SUMS ({actual})");
    Ok(())
}

/// Namespaced immutable tag recording one starter revision (doc-10 "Validation and evidence").
#[must_use]
pub fn starter_tag(release_tag: &str) -> String {
    format!("pixi-sandbox-{release_tag}")
}

/// Decide whether a release is a publishable source for a starter revision.
///
/// Pure so the fail-closed rules are testable without a network: a draft, a tag that names a
/// different commit than the one handed off, or a missing asset each has to be a finding
/// rather than a silent pass (TASK-74 AC#4).
#[must_use]
pub fn release_findings(
    tag: &str,
    expected_commit: &str,
    is_draft: bool,
    tag_commit: Option<&str>,
    asset_names: &[String],
) -> Vec<String> {
    let mut findings = Vec::new();
    if !is_strict_tag(tag) {
        findings.push(format!("{tag:?} is not a strict semver tag like v1.2.3"));
    }
    if is_draft {
        findings.push(format!("{tag} is still a draft release"));
    }
    match tag_commit {
        None => findings.push(format!("{tag} does not resolve to a commit")),
        Some(actual) if !commit_matches(actual, expected_commit) => {
            findings.push(format!(
                "{tag} resolves to {actual}, not the handed-off commit {expected_commit}"
            ));
        }
        Some(_) => {}
    }
    if !asset_names.iter().any(|a| a == "SHA256SUMS") {
        findings.push(format!("{tag} has no SHA256SUMS asset"));
    }
    if !asset_names.iter().any(|a| a.starts_with("pixi-sandbox-")) {
        findings.push(format!("{tag} has no standalone pixi-sandbox asset"));
    }
    findings
}

/// Check, over the network, that `tag` is a published release of `repo` at `expected_commit`.
///
/// Two `gh` reads, each feeding the pure [`release_findings`] above: the release itself (for
/// draft status and the asset list) and the tag's resolved commit. Resolving through the
/// commits endpoint rather than `targetCommitish` is deliberate — `targetCommitish` can be a
/// branch name, while `repos/{repo}/commits/{tag}` always dereferences to the commit.
///
/// # Errors
///
/// Fails when `gh` cannot be run or its output cannot be parsed, or when the release fails a finding: it is a draft, it lacks assets, or its tag does not resolve to `expected_commit`.
pub fn verify_release(repo: &str, tag: &str, expected_commit: &str) -> Result<()> {
    use std::process::Command as StdCommand;
    let release = StdCommand::new("gh")
        .args([
            "release",
            "view",
            tag,
            "--repo",
            repo,
            "--json",
            "isDraft,assets",
        ])
        .output()
        .context("starting gh release view")?;
    if !release.status.success() {
        bail!(
            "{tag} is not a published release of {repo}: {}",
            String::from_utf8_lossy(&release.stderr).trim()
        );
    }
    let parsed: serde_json::Value =
        serde_json::from_slice(&release.stdout).context("parsing gh release view output")?;
    let is_draft = parsed["isDraft"].as_bool().unwrap_or(true);
    let assets: Vec<String> = parsed["assets"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(|x| x["name"].as_str().map(ToString::to_string))
                .collect()
        })
        .unwrap_or_default();

    let tag_commit = resolve_tag_commit(repo, tag)?;

    let findings = release_findings(
        tag,
        expected_commit,
        is_draft,
        tag_commit.as_deref(),
        &assets,
    );
    if !findings.is_empty() {
        for finding in &findings {
            eprintln!("::error::{finding}");
        }
        bail!(
            "{} release finding(s); refusing to touch the starter",
            findings.len()
        );
    }
    println!("{tag} is a published release of {repo} at {expected_commit}");
    Ok(())
}

/// The commit a release tag dereferences to, or `None` when GitHub has no such commit.
///
/// Resolved through the commits endpoint rather than a release's `targetCommitish`, which can be
/// a branch name. Both the release hand-off and the dispatch guard ask this one question, so it
/// is asked in one place.
fn resolve_tag_commit(repo: &str, tag: &str) -> Result<Option<String>> {
    use std::process::Command;
    let output = Command::new("gh")
        .args([
            "api",
            &format!("repos/{repo}/commits/{tag}"),
            "--jq",
            ".sha",
        ])
        .output()
        .context("starting gh api for the tag's commit")?;
    if !output.status.success() {
        return Ok(None);
    }
    let text = String::from_utf8_lossy(&output.stdout).trim().to_string();
    Ok((!text.is_empty()).then_some(text))
}

/// Do these two spellings name the same commit?
///
/// Either side may be the short form: a dispatch carries the seven characters the UI offers, a
/// release endpoint returns the full sha. Prefix agreement is the whole rule, in both directions.
fn commit_matches(a: &str, b: &str) -> bool {
    a.starts_with(b) || b.starts_with(a)
}

/// Decide whether a `starter` dispatch may start work at all, from what the tag resolves to.
///
/// The guard runs as the workflow's first job, before the starter repository is checked out or
/// scaffolded (task-85 AC#4): a mismatch used to surface only after the lane had spent a full job
/// start learning that the release it was handed was not the one the operator meant. The message
/// therefore names both commits and states which one to pass.
#[must_use]
pub fn dispatch_findings(
    tag: &str,
    expected_commit: &str,
    resolved_commit: Option<&str>,
) -> Vec<String> {
    let mut findings = Vec::new();
    if !is_strict_tag(tag) {
        findings.push(format!(
            "{tag:?} is not a strict semver tag like v1.2.3, so it names no release to build a starter from"
        ));
    }
    match resolved_commit {
        None => findings.push(format!(
            "{tag} does not resolve to a commit, so the dispatched source-commit {expected_commit} \
             cannot be checked against it; pass a published release tag"
        )),
        Some(actual) if !commit_matches(actual, expected_commit) => findings.push(format!(
            "{tag} names {actual}, but the dispatch handed off {expected_commit}; the starter is \
             generated from the release, so re-dispatch with source-commit {actual} or choose the \
             release built from {expected_commit}"
        )),
        Some(_) => {}
    }
    findings
}

/// The one line an accepted dispatch leaves in the log and the job summary.
///
/// Reporting the agreement is the point: the task was written from a run where nothing told the
/// operator which commit the tag actually names.
#[must_use]
pub fn dispatch_report(tag: &str, resolved_commit: &str) -> String {
    format!("{tag} names commit {resolved_commit}, and the dispatch agrees")
}

/// Check, over the network, that a starter dispatch names the commit its release tag points at.
///
/// # Errors
///
/// Fails when the tag cannot be resolved through `gh`, or when the dispatch names a commit other than the one the tag points at. The refusal is annotated and summarised first.
pub fn check_dispatch(repo: &str, tag: &str, expected_commit: &str) -> Result<()> {
    let resolved = resolve_tag_commit(repo, tag)?;
    let findings = dispatch_findings(tag, expected_commit, resolved.as_deref());
    if !findings.is_empty() {
        for finding in &findings {
            eprintln!("::error::{finding}");
        }
        crate::util::github_summary(&format!(
            "## Starter dispatch refused\n\n- release tag `{tag}`\n- dispatched commit `{expected_commit}`\n\n{}",
            findings.join("\n")
        ));
        bail!(
            "{} dispatch finding(s); no starter work was started",
            findings.len()
        );
    }
    // The findings are empty, so a commit came back; the dispatched spelling is the fallback only
    // for the case the guard already refuses.
    let report = dispatch_report(tag, resolved.as_deref().unwrap_or(expected_commit));
    println!("{report} ({repo})");
    crate::util::github_summary(&format!("## Starter dispatch\n\n- {report}\n"));
    Ok(())
}

/// Check that the canonical starter already has a real `main` commit before attempting checkout.
///
/// `default_branch` is repository metadata, not proof that a branch ref exists: GitHub can
/// report `main` for a repository with no commits. The initial seed is an owner action, never
/// an automation permission. This check is deliberately against the ref endpoint so an empty
/// repository fails before the workflow attempts checkout.
///
/// # Errors
///
/// Fails when `gh api` cannot be started, or when the starter repository has no `refs/heads/main` ref.
pub fn check_main_ref(repo: &str) -> Result<()> {
    use std::process::Command;

    let endpoint = format!("repos/{repo}/git/ref/heads/main");
    let output = Command::new("gh")
        .args(["api", &endpoint])
        .output()
        .context("starting gh api to check the starter main ref")?;
    let sha = parse_main_ref(
        repo,
        output.status.success(),
        &output.stdout,
        &output.stderr,
    )?;
    println!("starter {repo} has refs/heads/main at {sha}");
    Ok(())
}

#[doc(hidden)] // test boundary (tests/starter.rs)
pub fn parse_main_ref(repo: &str, succeeded: bool, stdout: &[u8], stderr: &[u8]) -> Result<String> {
    if !succeeded {
        let detail = String::from_utf8_lossy(stderr).trim().to_string();
        let detail = if detail.is_empty() {
            "GitHub did not provide an error detail".to_string()
        } else {
            detail
        };
        bail!(
            "starter repository {repo} has no readable commit at refs/heads/main; an owner must seed main with an initial commit before this workflow can continue (a configured default branch does not prove that the ref exists): {detail}"
        );
    }

    let response: serde_json::Value =
        serde_json::from_slice(stdout).context("parsing the starter main-ref response")?;
    if response["ref"].as_str() != Some("refs/heads/main") {
        bail!(
            "GitHub did not return refs/heads/main for starter repository {repo}; an owner must seed main with an initial commit before this workflow can continue"
        );
    }
    let Some(sha) = response["object"]["sha"]
        .as_str()
        .filter(|sha| !sha.trim().is_empty())
    else {
        bail!(
            "starter repository {repo} returned no commit for refs/heads/main; an owner must seed main with an initial commit before this workflow can continue"
        );
    };
    Ok(sha.to_string())
}

/// Materialise the tree `dir` would commit into a scratch repository at `out/seed`, commit it,
/// and return a fresh clone of that commit at `out/starter`.
///
/// This is what makes the starter's development-task proof mean something: a user gets a clone of
/// the revision, not the directory the lane just finished writing into. The clone is therefore
/// built from the same answer [`verify`] consults — `git`'s, not the filesystem's — and shares no
/// objects with the source tree (see `ShellGit::clone_fresh`).
///
/// `out` must be absent or empty. A proof that quietly reused a previous attempt's directory would
/// be a proof about two trees at once.
///
/// # Errors
///
/// Fails when `dir` is not a publishable starter revision, when `out` exists and is not empty, or when the scratch repository cannot be created, committed, or cloned.
pub fn clone_publishable(dir: &Path, out: &Path) -> Result<PathBuf> {
    use pixi_sandbox_git::ShellGit;
    let git = ShellGit::new();
    if !git.is_work_tree(dir)? {
        bail!(
            "{} is not a git work tree, so the tree the starter would publish cannot be assembled; \
             run this step against the starter checkout the workflow created",
            dir.display()
        );
    }
    let paths = git.ls_publishable(dir)?;
    if paths.is_empty() {
        bail!(
            "starter tree {} would commit no files at all, so there is nothing to prove in a clone",
            dir.display()
        );
    }
    if out.exists() && std::fs::read_dir(out)?.next().is_some() {
        bail!(
            "{} is not empty; the clone proof writes into a scratch directory of its own",
            out.display()
        );
    }

    let seed = out.join("seed");
    let clone = out.join("starter");
    std::fs::create_dir_all(&seed).with_context(|| format!("creating {}", seed.display()))?;
    for rel in &paths {
        let from = dir.join(rel);
        let to = seed.join(rel);
        if let Some(parent) = to.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        std::fs::copy(&from, &to)
            .with_context(|| format!("staging {} for the clone", from.display()))?;
        keep_executable_bit(&from, &to)?;
    }
    git.init_repo(&seed)?;
    git.add_files(&seed, &paths)?;
    git.commit(&seed, "starter clone proof")?;
    git.clone_fresh(&seed, &clone)?;
    println!(
        "assembled {} file(s) from {} into a fresh clone at {}",
        paths.len(),
        dir.display(),
        clone.display()
    );
    Ok(clone)
}

/// Carry the one mode bit `git` itself records.
///
/// A copied launcher that lost its executable bit would clone into a tree a user cannot run, and
/// the proof would then be measuring the copy rather than the starter. Sizes, times and the rest
/// of the mode are not in the revision, so they are deliberately not copied.
#[cfg(unix)]
fn keep_executable_bit(from: &Path, to: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mode = std::fs::metadata(from)
        .with_context(|| format!("reading the mode of {}", from.display()))?
        .permissions()
        .mode();
    if mode & 0o111 != 0 {
        std::fs::set_permissions(to, std::fs::Permissions::from_mode(0o755))
            .with_context(|| format!("marking {} executable", to.display()))?;
    }
    Ok(())
}

#[cfg(not(unix))]
fn keep_executable_bit(_from: &Path, _to: &Path) -> Result<()> {
    Ok(())
}

/// Is there anything to publish, and may we publish it here?
///
/// Separated from the git calls so the refusal rules can be tested directly. Returns the
/// files to stage; an empty list means the verified tag reproduced the current revision
/// exactly, which the publication contract requires to be a success, not a no-op failure.
#[doc(hidden)] // test boundary (tests/starter.rs)
#[must_use]
pub fn publish_refusals(
    remote: &str,
    starter_repo: &str,
    tag_exists: bool,
    tag: &str,
) -> Vec<String> {
    let mut refusals = Vec::new();
    if !remote.contains(starter_repo) {
        refusals.push(format!(
            "remote {remote:?} is not the canonical starter {starter_repo}; the starter lane must never push to a fork or a user's repository"
        ));
    }
    if tag_exists {
        refusals.push(format!(
            "{} already exists on the remote; starter revisions are immutable",
            starter_tag(tag)
        ));
    }
    refusals
}

/// Commit and push one validated starter revision.
///
/// Never force-pushes and never rewrites history (doc-10 "Credentials and safety"). A tree
/// identical to the published revision is an idempotent success.
///
/// # Errors
///
/// Fails when a publish refusal applies (for example, the immutable tag already exists on the remote), when git cannot report the remote tag or the worktree status, or when the commit or push fails.
pub fn publish(
    root: &Path,
    remote: &str,
    starter_repo: &str,
    tag: &str,
    branch: &str,
    source_commit: &str,
    dry_run: bool,
) -> Result<()> {
    use pixi_sandbox_git::ShellGit;
    let git = ShellGit::new();
    let immutable = starter_tag(tag);
    let refusals = publish_refusals(
        remote,
        starter_repo,
        git.remote_tag_exists(remote, &immutable)?,
        tag,
    );
    if !refusals.is_empty() {
        for refusal in &refusals {
            eprintln!("::error::{refusal}");
        }
        bail!("refusing to publish the starter; the previous revision is unchanged");
    }

    let changed = git.worktree_status_files(root)?;
    if changed.is_empty() {
        println!("starter is already at {tag}; nothing to publish (idempotent re-run)");
        return Ok(());
    }
    println!("publishing {} file(s) for {tag}", changed.len());
    if dry_run {
        println!("dry run: not committing or pushing");
        for file in &changed {
            println!("  would publish {file}");
        }
        return Ok(());
    }
    git.add_files(root, &changed)?;
    git.commit(
        root,
        &format!(
            "chore: regenerate starter for pixi-sandbox {tag}\n\nSource commit: {source_commit}"
        ),
    )?;
    git.tag_annotated(root, &immutable)?;
    git.push_refspec(root, remote, branch)?;
    git.push_refspec(root, remote, &format!("refs/tags/{immutable}"))?;
    crate::util::github_summary(&format!(
        "## Starter published\n\n- release `{tag}`\n- source commit `{source_commit}`\n- starter tag `{immutable}`\n"
    ));
    Ok(())
}
