//! Release-published starter scaffold (doc-10, TASK-74).
//!
//! The starter repository is a *consumer artifact*, not a second implementation of
//! pixi-sandbox: every file it owns is either generated by one published release of the CLI
//! or rendered here from that same release's tag. This module holds the half the CLI does not
//! generate — the Pixi project itself, the ignore file and the README — plus the validation
//! that the assembled tree really is pinned to one release.
//!
//! Why Rust and not the workflow: `consumer-proof.yml` already proves this recipe works, but
//! it spends ~60 lines of `run:` shell carrying `# multiline-run-allowed:` opt-outs to do it.
//! The repository's rule is that a workflow step is an action or a one-line task (task-36), so
//! the starter lane keeps its logic here where it is typed, unit-tested against tempdirs, and
//! shared by every runner instead of duplicated per shell dialect.

use anyhow::{Context, Result, bail};
use std::path::Path;

/// Files the starter owns that `pixi-sandbox init` does not write.
///
/// `init` owns the publisher, the relock workflow and the restore launcher, and writes a
/// default `pixi-sandbox.toml` once. Everything below is the Pixi project that gives those
/// files something to pack.
pub const SCAFFOLD_FILES: [&str; 3] = ["pixi.toml", ".gitignore", "README.md"];

/// Every file a validated starter revision must contain before it is published.
pub const REQUIRED_FILES: [&str; 7] = [
    "pixi.toml",
    "pixi.lock",
    "pixi-sandbox.toml",
    ".gitignore",
    "README.md",
    ".github/workflows/publish-sandbox.yml",
    ".github/workflows/relock.yml",
];

/// Paths that must never be committed to the starter: runtime state, caches and anything
/// that could carry a credential (doc-10 "Credentials and safety").
pub const FORBIDDEN_PATHS: [&str; 6] = [
    ".pixi",
    ".pixi-sandbox",
    ".env",
    "SHA256SUMS",
    "pixi-sandbox",
    "pixi-sandbox.exe",
];

/// Strip a leading `v` so a tag and a CLI version can be compared.
///
/// The release tag is `v1.2.3`; the generated publisher stamps the bare `1.2.3`. Comparing
/// them is the whole point of [`verify`], so the two spellings are normalised in one place.
#[must_use]
pub fn version_of(tag: &str) -> &str {
    tag.strip_prefix('v').unwrap_or(tag)
}

/// The starter's Pixi project.
///
/// Deliberately language-neutral (doc-10 "Template ownership and contents"): it supplies the
/// Pixi/Sandbox scaffold and one documented development task, not a framework starter. The
/// single dependency is not decoration — a dependency-free environment solves to no
/// platform-specific lock entry at all, and `pixi-pack` then fails with "platform not found in
/// lockfile: linux-64". `consumer-proof.yml` hit exactly that and picked `ripgrep` for the same
/// reason; keeping the same choice keeps the two lanes comparable.
#[must_use]
pub fn render_pixi_toml(name: &str) -> String {
    format!(
        "# Pixi project for the pixi-sandbox starter. Replace this with your own project:\n\
         # the only parts Pixi Sandbox needs are a workspace with at least one real dependency\n\
         # and a platform that matches the `[[bundle]]` in pixi-sandbox.toml.\n\
         [workspace]\n\
         name = \"{name}\"\n\
         channels = [\"https://prefix.dev/conda-forge\"]\n\
         platforms = [\"linux-64\"]\n\
         \n\
         [dependencies]\n\
         # One small, fast-to-fetch package keeps the environment real. A dependency-free\n\
         # workspace produces a lockfile with no per-platform data, which packs into a\n\
         # transport that cannot be restored.\n\
         ripgrep = \"*\"\n\
         \n\
         [tasks]\n\
         # The documented development command. `pixi run dev` is what the README tells a new\n\
         # user to run, and what CI runs to prove a fresh clone works.\n\
         dev = \"rg --version\"\n"
    )
}

/// The starter's ignore file.
///
/// `.pixi/` and `.pixi-sandbox/` are restored runtime state, not sources. Committing either
/// would ship a stale environment to everyone who uses the template.
#[must_use]
pub fn render_gitignore() -> String {
    "# Pixi's installed environments: restored from pixi.lock, never committed.\n\
     .pixi/\n\
     \n\
     # Pixi Sandbox runtime state: transports, vendored crates and downloaded tools.\n\
     .pixi-sandbox/\n\
     \n\
     # A downloaded standalone binary and its checksum manifest are build inputs, not sources.\n\
     /pixi-sandbox\n\
     /pixi-sandbox.exe\n\
     /SHA256SUMS\n"
        .to_string()
}

/// The starter README.
///
/// doc-10 requires the prose to state the release it corresponds to and to cross-link the main
/// project, so a user can tell exactly which pixi-sandbox created their scaffold.
#[must_use]
pub fn render_readme(
    tag: &str,
    source_commit: &str,
    source_repo: &str,
    starter_repo: &str,
) -> String {
    let version = version_of(tag);
    format!(
        "# pixi-sandbox starter\n\
         \n\
         A ready-to-run [Pixi](https://pixi.sh) project with\n\
         [Pixi Sandbox]({server}/{source_repo}) already configured. Everything in this\n\
         repository is generated from one published release — there is no setup step.\n\
         \n\
         | | |\n\
         |---|---|\n\
         | pixi-sandbox release | [`{tag}`]({server}/{source_repo}/releases/tag/{tag}) |\n\
         | source commit | [`{short}`]({server}/{source_repo}/commit/{source_commit}) |\n\
         | starter repository | [{starter_repo}]({server}/{starter_repo}) |\n\
         \n\
         ## Use it\n\
         \n\
         1. Press **Use this template** and create a repository under your own owner.\n\
         2. Clone it and run the development task:\n\
         \n\
         ```sh\n\
         pixi run dev\n\
         ```\n\
         \n\
         3. Push to `main`. The included publisher packs your locked environment and pushes a\n\
            self-contained sandbox branch, using your repository's own `GITHUB_TOKEN`.\n\
         \n\
         No `pixi-sandbox init`, no workflow copying, no version to choose, and no token owned\n\
         by anyone else.\n\
         \n\
         ## What is generated\n\
         \n\
         These files are owned by pixi-sandbox `{version}` and are regenerated by\n\
         `pixi-sandbox init`. Edit them only if you are ready to own them:\n\
         \n\
         - `.github/workflows/publish-sandbox.yml` — packs and publishes the sandbox branch\n\
         - `.github/workflows/relock.yml` — refreshes `pixi.lock` on pull requests\n\
         - `restore.sh` — offline restore launcher for an airlocked host\n\
         - `pixi-sandbox.toml` — the reviewed publish plan; written once, then yours\n\
         \n\
         `pixi.toml`, `pixi.lock`, `.gitignore` and this README are yours from the start.\n\
         \n\
         ## Updating\n\
         \n\
         This repository is a snapshot of `{tag}`. A newer pixi-sandbox release produces a new\n\
         starter revision; it does not change repositories already created from this template.\n\
         Your own repository upgrades itself through the weekly upgrade lane in the publisher\n\
         workflow, which opens a reviewable pull request.\n",
        server = "https://github.com",
        short = &source_commit[..source_commit.len().min(7)],
    )
}

/// Write the three scaffold files into `out`.
///
/// Idempotent by construction: every byte is derived from the arguments, so a second call with
/// the same inputs produces the same tree. That is what makes the publication contract's
/// "rerunning the same verified tag produces no content change" testable.
pub fn scaffold(
    out: &Path,
    name: &str,
    tag: &str,
    source_commit: &str,
    source_repo: &str,
    starter_repo: &str,
) -> Result<()> {
    if !is_strict_tag(tag) {
        bail!("starter tag must be a strict semver tag like v1.2.3, got {tag:?}");
    }
    if source_commit.len() < 7 || !source_commit.chars().all(|c| c.is_ascii_hexdigit()) {
        bail!("starter source commit must be a hex sha of at least 7 chars, got {source_commit:?}");
    }
    std::fs::create_dir_all(out).with_context(|| format!("creating {}", out.display()))?;
    crate::util::write_atomic(&out.join("pixi.toml"), &render_pixi_toml(name))?;
    crate::util::write_atomic(&out.join(".gitignore"), &render_gitignore())?;
    crate::util::write_atomic(
        &out.join("README.md"),
        &render_readme(tag, source_commit, source_repo, starter_repo),
    )?;
    println!("scaffolded starter for {tag} in {}", out.display());
    Ok(())
}

/// `v1.2.3` and nothing looser. A starter revision that cannot name an exact release is not
/// publishable (doc-10 "Validation and evidence" item 1).
fn is_strict_tag(tag: &str) -> bool {
    crate::util::is_strict_semver(version_of(tag))
}

/// Report every reason `dir` is not a publishable starter revision for `tag`.
///
/// Returns findings rather than failing on the first one, for the same reason
/// `check-repository` does: one run should tell you everything that is wrong (D13).
pub fn verify(dir: &Path, tag: &str) -> Result<Vec<String>> {
    let mut findings = Vec::new();
    if !is_strict_tag(tag) {
        findings.push(format!(
            "tag {tag:?} is not a strict semver tag like v1.2.3"
        ));
        return Ok(findings);
    }
    let version = version_of(tag);

    for required in REQUIRED_FILES {
        if !dir.join(required).exists() {
            findings.push(format!("missing required file {required}"));
        }
    }
    for forbidden in FORBIDDEN_PATHS {
        if dir.join(forbidden).exists() {
            findings.push(format!(
                "{forbidden} must not be committed to the starter (runtime state or credential)"
            ));
        }
    }

    let workflow_path = dir.join(".github/workflows/publish-sandbox.yml");
    if workflow_path.exists() {
        let workflow = crate::util::read(&workflow_path)?;
        let marker = format!("# pixi-sandbox-version: {version}");
        if !workflow.lines().any(|line| line.trim() == marker) {
            findings.push(format!(
                "publisher does not carry the {marker:?} marker, so it was not generated by {tag}"
            ));
        }
        let env_pin = format!("PIXI_SANDBOX_VERSION: {version}");
        if !workflow.lines().any(|line| line.trim() == env_pin) {
            findings.push(format!("publisher does not pin {env_pin:?}"));
        }
        findings.extend(floating_version_findings(&workflow, "publisher"));
    }

    let readme_path = dir.join("README.md");
    if readme_path.exists() {
        let readme = crate::util::read(&readme_path)?;
        if !readme.contains(tag) {
            findings.push(format!("README does not state the release tag {tag}"));
        }
    }
    Ok(findings)
}

/// Lines that resolve a *version* as `latest` rather than pinning one.
///
/// A blanket search for `latest` is wrong here: `runs-on: ubuntu-latest` is a runner label, not
/// a version resolution, and it appears in every generated workflow. Only the spellings that
/// would actually float a pixi-sandbox version are findings.
fn floating_version_findings(text: &str, what: &str) -> Vec<String> {
    const FLOATING: [&str; 4] = ["releases/latest", "==latest", "--version latest", "@latest"];
    crate::util::lines_without_opt_out(text)
        .filter_map(|(number, line)| {
            FLOATING
                .iter()
                .find(|needle| line.contains(**needle))
                .map(|needle| {
                    format!("{what} line {number} resolves a floating version ({needle})")
                })
        })
        .collect()
}

/// Verify a downloaded release asset against the release's own `SHA256SUMS`.
///
/// `gh release download` is HTTPS and authenticated, but doc-10 requires the checksum manifest
/// to be *checked*, not merely present: the starter's whole claim is that it was generated by a
/// specific, verified binary.
pub fn verify_asset(binary: &Path, sums: &Path, asset_name: &str) -> Result<()> {
    let sums_text = crate::util::read(sums)?;
    let expected = sums_text
        .lines()
        .find_map(|line| {
            let (digest, name) = line.split_once("  ")?;
            (name.trim() == asset_name).then_some(digest.trim())
        })
        .with_context(|| format!("{asset_name} has no line in {}", sums.display()))?;
    let actual = pixi_sandbox_core::shard::sha256_file(binary)
        .with_context(|| format!("hashing {}", binary.display()))?;
    if !actual.eq_ignore_ascii_case(expected) {
        bail!(
            "checksum mismatch for {asset_name}: SHA256SUMS says {expected}, downloaded file is {actual}"
        );
    }
    println!("verified {asset_name} against SHA256SUMS ({actual})");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const TAG: &str = "v1.2.3";
    const COMMIT: &str = "8193c58068c3245e5267c4c604f989237e4d6e49";
    const SOURCE: &str = "Archont561/pixi-sandbox";
    const STARTER: &str = "Archont561/pixi-sandbox-starter";

    /// A starter whose publisher came from a different release is the one failure the whole
    /// publication contract exists to prevent, so the marker check is exact, not a substring.
    #[test]
    fn a_publisher_from_another_release_is_reported() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_starter(dir.path(), "9.9.9");
        let findings = verify(dir.path(), TAG).unwrap();
        assert!(
            findings
                .iter()
                .any(|f| f.contains("pixi-sandbox-version: 1.2.3")),
            "{findings:?}"
        );
    }

    #[test]
    fn a_complete_starter_for_its_own_tag_has_no_findings() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_starter(dir.path(), "1.2.3");
        assert_eq!(verify(dir.path(), TAG).unwrap(), Vec::<String>::new());
    }

    #[test]
    fn every_required_file_is_reported_when_absent() {
        let dir = tempfile::tempdir().unwrap();
        let findings = verify(dir.path(), TAG).unwrap();
        for required in REQUIRED_FILES {
            assert!(
                findings.iter().any(|f| f.contains(required)),
                "{required} not reported in {findings:?}"
            );
        }
    }

    /// Runtime state is the thing a template must never ship: a committed `.pixi/` hands every
    /// user a stale environment that their own lockfile then disagrees with.
    #[test]
    fn committed_runtime_state_is_reported() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_starter(dir.path(), "1.2.3");
        std::fs::create_dir_all(dir.path().join(".pixi")).unwrap();
        std::fs::write(dir.path().join("SHA256SUMS"), "x").unwrap();
        let findings = verify(dir.path(), TAG).unwrap();
        assert!(findings.iter().any(|f| f.contains(".pixi")), "{findings:?}");
        assert!(
            findings.iter().any(|f| f.contains("SHA256SUMS")),
            "{findings:?}"
        );
    }

    /// `ubuntu-latest` is a runner label and must not be mistaken for a floating version —
    /// every generated workflow contains it, so a blanket `latest` search would fail them all.
    #[test]
    fn a_runner_label_is_not_a_floating_version() {
        assert!(floating_version_findings("    runs-on: ubuntu-latest\n", "w").is_empty());
    }

    #[test]
    fn each_floating_version_spelling_is_reported() {
        for needle in ["releases/latest", "==latest", "--version latest", "@latest"] {
            let findings = floating_version_findings(&format!("  x {needle} y\n"), "w");
            assert_eq!(findings.len(), 1, "{needle} not reported");
        }
    }

    /// Idempotence is the publication contract's core promise: rerunning a verified tag must
    /// produce no content change.
    #[test]
    fn scaffolding_twice_is_byte_identical() {
        let dir = tempfile::tempdir().unwrap();
        scaffold(dir.path(), "starter", TAG, COMMIT, SOURCE, STARTER).unwrap();
        let first: Vec<String> = SCAFFOLD_FILES
            .iter()
            .map(|f| std::fs::read_to_string(dir.path().join(f)).unwrap())
            .collect();
        scaffold(dir.path(), "starter", TAG, COMMIT, SOURCE, STARTER).unwrap();
        let second: Vec<String> = SCAFFOLD_FILES
            .iter()
            .map(|f| std::fs::read_to_string(dir.path().join(f)).unwrap())
            .collect();
        assert_eq!(first, second);
    }

    #[test]
    fn a_loose_tag_is_refused_before_anything_is_written() {
        let dir = tempfile::tempdir().unwrap();
        for tag in ["latest", "v1.2", "1.2.3.4", ""] {
            assert!(
                scaffold(dir.path(), "starter", tag, COMMIT, SOURCE, STARTER).is_err(),
                "{tag:?} was accepted"
            );
        }
        assert!(!dir.path().join("pixi.toml").exists());
    }

    #[test]
    fn a_non_hex_source_commit_is_refused() {
        let dir = tempfile::tempdir().unwrap();
        assert!(scaffold(dir.path(), "starter", TAG, "not-a-sha", SOURCE, STARTER).is_err());
    }

    #[test]
    fn the_readme_names_the_release_and_the_commit() {
        let readme = render_readme(TAG, COMMIT, SOURCE, STARTER);
        assert!(readme.contains(TAG));
        assert!(readme.contains(&COMMIT[..7]));
        assert!(readme.contains(STARTER));
        assert!(readme.contains("Use this template"));
    }

    /// The scaffolded project must declare a real dependency: a dependency-free workspace
    /// locks to no per-platform entry and packs into an unrestorable transport.
    #[test]
    fn the_scaffolded_project_declares_a_real_dependency_and_a_dev_task() {
        let rendered = render_pixi_toml("starter");
        let parsed: toml::Value = toml::from_str(&rendered).unwrap();
        assert!(
            parsed["dependencies"]
                .as_table()
                .is_some_and(|d| !d.is_empty()),
            "no dependency declared"
        );
        assert!(parsed["tasks"]["dev"].is_str());
        assert_eq!(
            parsed["workspace"]["platforms"][0].as_str(),
            Some("linux-64")
        );
    }

    #[test]
    fn the_gitignore_excludes_every_forbidden_runtime_path() {
        let ignore = render_gitignore();
        for path in [".pixi/", ".pixi-sandbox/", "SHA256SUMS"] {
            assert!(ignore.contains(path), "{path} missing from .gitignore");
        }
    }

    #[test]
    fn a_tampered_asset_fails_its_checksum() {
        let dir = tempfile::tempdir().unwrap();
        let binary = dir.path().join("pixi-sandbox-x86_64-unknown-linux-musl");
        std::fs::write(&binary, b"real bytes").unwrap();
        let digest = pixi_sandbox_core::shard::sha256_file(&binary).unwrap();
        let sums = dir.path().join("SHA256SUMS");
        std::fs::write(
            &sums,
            format!("{digest}  pixi-sandbox-x86_64-unknown-linux-musl\n"),
        )
        .unwrap();
        verify_asset(&binary, &sums, "pixi-sandbox-x86_64-unknown-linux-musl").unwrap();

        std::fs::write(&binary, b"tampered").unwrap();
        assert!(verify_asset(&binary, &sums, "pixi-sandbox-x86_64-unknown-linux-musl").is_err());
    }

    #[test]
    fn an_asset_absent_from_the_checksum_manifest_is_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let binary = dir.path().join("bin");
        std::fs::write(&binary, b"x").unwrap();
        let sums = dir.path().join("SHA256SUMS");
        std::fs::write(&sums, "deadbeef  some-other-asset\n").unwrap();
        assert!(verify_asset(&binary, &sums, "pixi-sandbox-x86_64-unknown-linux-musl").is_err());
    }

    fn write_valid_starter(dir: &Path, workflow_version: &str) {
        scaffold(dir, "starter", TAG, COMMIT, SOURCE, STARTER).unwrap();
        std::fs::create_dir_all(dir.join(".github/workflows")).unwrap();
        std::fs::write(dir.join("pixi.lock"), "version: 6\n").unwrap();
        std::fs::write(dir.join("pixi-sandbox.toml"), "schema = 1\n").unwrap();
        std::fs::write(
            dir.join(".github/workflows/publish-sandbox.yml"),
            format!(
                "# Generated by pixi-sandbox init\n\
                 # pixi-sandbox-version: {workflow_version}\n\
                 name: publish sandbox\n\
                 env:\n  PIXI_SANDBOX_VERSION: {workflow_version}\n\
                 jobs:\n  x:\n    runs-on: ubuntu-latest\n"
            ),
        )
        .unwrap();
        std::fs::write(dir.join(".github/workflows/relock.yml"), "name: relock\n").unwrap();
    }
}
