use anyhow::{Context, Result, bail};
use pixi_sandbox::generated::{GithubWorkflowOptions, render_github_workflow};
use std::fs;
use std::path::Path;
use std::process::Command;

const WORKFLOW_PATH: &str = ".github/workflows/publish-sandbox.yml";

/// Validate the exact workflow renderer used by `pixi-sandbox init` with GitHub's external
/// workflow linter. Structural contracts that actionlint cannot evaluate live in the product
/// crate's Rust tests; this adapter owns only temporary-project and process orchestration.
pub fn lint_generated_workflow(actionlint: &Path) -> Result<()> {
    let project = tempfile::tempdir().context("creating a temporary generated project")?;
    let workflow_path = project.path().join(WORKFLOW_PATH);
    let parent = workflow_path
        .parent()
        .context("generated workflow path has no parent")?;
    fs::create_dir_all(parent)
        .with_context(|| format!("creating generated workflow directory {}", parent.display()))?;

    let workflow = render_github_workflow(GithubWorkflowOptions {
        version: env!("CARGO_PKG_VERSION"),
        config_path: "pixi-sandbox.toml",
    });
    fs::write(&workflow_path, workflow)
        .with_context(|| format!("writing generated workflow {}", workflow_path.display()))?;

    run_actionlint(actionlint, project.path(), Path::new(WORKFLOW_PATH))?;
    eprintln!("generated workflow: actionlint clean (Rust tests cover matrix shape and plan keys)");
    Ok(())
}

fn run_actionlint(actionlint: &Path, project: &Path, workflow: &Path) -> Result<()> {
    let workflow_path = project.join(workflow);
    if !workflow_path.is_file() {
        bail!(
            "generated workflow is missing at {} — the renderer did not create the artifact actionlint must check",
            workflow_path.display()
        );
    }

    let output = Command::new(actionlint)
        .arg(workflow)
        .current_dir(project)
        .output()
        .with_context(|| {
            format!(
                "starting {} — actionlint is required; run this command inside the Pixi environment",
                actionlint.display()
            )
        })?;

    if !output.status.success() {
        bail!(
            "actionlint rejects the workflow generated by pixi-sandbox (status {}):\n{}{}",
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{WORKFLOW_PATH, run_actionlint};
    use std::fs;
    use std::path::Path;

    #[test]
    fn a_missing_generated_file_names_the_expected_artifact() {
        let project = tempfile::tempdir().expect("temp project");
        let error = run_actionlint(
            Path::new("actionlint-does-not-run"),
            project.path(),
            Path::new(WORKFLOW_PATH),
        )
        .expect_err("the absent workflow must fail before actionlint starts");
        let message = format!("{error:#}");
        assert!(
            message.contains("generated workflow is missing"),
            "{message}"
        );
        assert!(message.contains(WORKFLOW_PATH), "{message}");
    }

    #[test]
    fn missing_actionlint_names_the_required_tool_and_environment() {
        let project = tempfile::tempdir().expect("temp project");
        let workflow = project.path().join(WORKFLOW_PATH);
        fs::create_dir_all(workflow.parent().expect("workflow parent"))
            .expect("workflow directory");
        fs::write(&workflow, "name: fixture\n").expect("fixture workflow");

        let error = run_actionlint(
            Path::new("actionlint-does-not-exist-for-this-test"),
            project.path(),
            Path::new(WORKFLOW_PATH),
        )
        .expect_err("the deliberately absent actionlint must fail");
        let message = format!("{error:#}");
        assert!(message.contains("actionlint is required"), "{message}");
        assert!(message.contains("Pixi environment"), "{message}");
    }
}
