//! `repo_checks::workflow_shape` (moved from the module's inline `#[cfg(test)]`, TASK-83:
//! names kept, bodies verbatim).

mod support;

use std::fs;
use support::{headlines, valid_fixture};
use xtask::repo_checks::workflow_shape::MULTI_RUN_ALLOWED;

#[test]
fn a_multi_line_run_block_fires_check_9() {
    let dir = valid_fixture();
    fs::write(
        dir.path().join(".github/workflows/shape.yml"),
        "jobs:\n  x:\n    steps:\n      - name: two commands\n        run: |\n          pixi run build\n          pixi run test\n",
    )
    .expect("workflow");
    let found = headlines(dir.path());
    assert!(
        found.iter().any(|h| h.contains("multi-line command block")),
        "{found:?}"
    );
}

#[test]
fn every_single_command_spelling_passes_check_9() {
    let dir = valid_fixture();
    // One literal command, a folded scalar (folds to one command however it wraps), a
    // backslash-continued single command, and plain one-line runs: all legal.
    let workflow = concat!(
        "jobs:\n  x:\n    steps:\n",
        "      - name: one literal\n        run: |\n          pixi run test\n",
        "      - name: folded\n        run: >-\n          pixi global install\n          --channel conda-forge\n          pixi-sandbox\n",
        "      - name: continued\n        run: |\n          pixi upload prefix \\\n            --channel example \\\n            dist/*.conda\n",
        "      - run: pixi run lint\n",
        "      - run: rustup target add x86_64-unknown-linux-musl\n",
    );
    fs::write(dir.path().join(".github/workflows/shape.yml"), workflow).expect("workflow");
    let found = headlines(dir.path());
    assert!(
        !found.iter().any(|h| h.contains("multi-line command block")),
        "single commands in every spelling must pass: {found:?}"
    );
}

#[test]
fn comments_and_blank_lines_inside_a_block_are_not_commands() {
    let dir = valid_fixture();
    fs::write(
        dir.path().join(".github/workflows/shape.yml"),
        "jobs:\n  x:\n    steps:\n      - run: |\n          # why this is fine\n\n          pixi run test\n",
    )
    .expect("workflow");
    let found = headlines(dir.path());
    assert!(
        !found.iter().any(|h| h.contains("multi-line command block")),
        "a commented single command is one command: {found:?}"
    );
}

/// TASK-76 AC#6: the blanket generated-marker exemption is gone. An `init`-marked artifact
/// (the marker `init` itself uses to decide a file is its own, in its header window) no longer
/// silences check 9 — the generated publisher passes the rule unaided, so the exemption
/// would only hide a regression. A multi-line block fires however the file is marked.
#[test]
fn a_generated_marker_no_longer_exempts_a_multi_line_block() {
    let block = "          pixi run build\n          pixi run test\n";
    let dir = valid_fixture();
    fs::write(
        dir.path().join(".github/workflows/shape.yml"),
        format!(
            "# Generated by pixi-sandbox init. Regenerate this file instead of editing it.\n\
             name: publish sandbox\njobs:\n  x:\n    steps:\n      - run: |\n{block}"
        ),
    )
    .expect("workflow");
    let found = headlines(dir.path());
    assert!(
        found.iter().any(|h| h.contains("multi-line command block")),
        "the generated marker is an ownership signal, not a shape exemption: {found:?}"
    );
}

/// The named exception is the marker with its reason: a step that deliberately carries a
/// multi-line block states so, and only that step is silenced.
#[test]
fn the_named_marker_is_the_only_exception_left() {
    let block = "          pixi run build\n          pixi run test\n";
    let dir = valid_fixture();
    fs::write(
        dir.path().join(".github/workflows/shape.yml"),
        format!(
            "jobs:\n  x:\n    steps:\n      # {MULTI_RUN_ALLOWED}: reviewed host bootstrap, pixi cannot provide it\n      - run: |\n{block}"
        ),
    )
    .expect("workflow");
    let found = headlines(dir.path());
    assert!(
        !found.iter().any(|h| h.contains("multi-line command block")),
        "the named exception carries its reason and silences the step: {found:?}"
    );
}

#[test]
fn the_opt_out_marker_silences_a_reviewed_multi_line_step() {
    let block = "          pixi run build\n          pixi run test\n";
    for (name, workflow) in [
        (
            "above",
            "jobs:\n  x:\n    steps:\n      # multiline-run-allowed: generated artifact\n      - run: |\n{block}".to_string(),
        ),
        (
            "inline",
            format!("jobs:\n  x:\n    steps:\n      - run: | # {MULTI_RUN_ALLOWED}\n{{block}}"),
        ),
        (
            "inside",
            format!("jobs:\n  x:\n    steps:\n      - run: |\n          # {MULTI_RUN_ALLOWED}\n{{block}}"),
        ),
    ] {
        let dir = valid_fixture();
        fs::write(
            dir.path().join(".github/workflows/shape.yml"),
            workflow.replace("{block}", block),
        )
        .expect("workflow");
        let found = headlines(dir.path());
        assert!(
            !found.iter().any(|h| h.contains("multi-line command block")),
            "the {name} marker placement must silence the step: {found:?}"
        );
    }
}
