[package]
name = "xtask"
description = "Repository automation for pixi-sandbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
pixi-sandbox = { path = "../pixi-sandbox", version = "0.4.2" }
pixi-sandbox-core = { path = "../pixi-sandbox-core", version = "0.4.2" }
pixi-sandbox-git = { path = "../pixi-sandbox-git", version = "0.4.2" }
regex = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
