//! The machine-readable version stamp every generated file carries beside the ownership marker
//! (task-47 AC#3 / decision D16): `pixi-sandbox-version: X.Y.Z`, within the same leading-line
//! window the ownership marker lives in, so `init --check` can read both with one short scan.

use pixi_sandbox::generated::{parse_version_stamp, version_stamp_line};

#[test]
fn the_stamp_line_round_trips_through_the_parser() {
    let line = version_stamp_line("1.2.3");
    assert_eq!(line, "pixi-sandbox-version: 1.2.3");
    let rendered = format!("# Generated by pixi-sandbox init.\n# {line}\nname: publish sandbox\n");
    assert_eq!(parse_version_stamp(&rendered), Some("1.2.3"));
}

#[test]
fn a_stamp_outside_the_marker_window_is_not_found() {
    let rendered = format!(
        "# line one\n# line two\n# line three\n# {}\n",
        version_stamp_line("9.9.9")
    );
    assert_eq!(parse_version_stamp(&rendered), None);
}

#[test]
fn a_file_with_no_stamp_parses_to_none() {
    assert_eq!(parse_version_stamp("#!/bin/sh\nset -eu\necho hi\n"), None);
}
