name: Build binaries

on:
  workflow_call:
    inputs:
      ref:
        description: Ref to build at
        required: false
        type: string
        default: ""
  pull_request:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "crates/**"
      - ".cargo/**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.triple }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - triple: x86_64-unknown-linux-musl
            runner: ubuntu-latest
          - triple: aarch64-unknown-linux-musl
            runner: ubuntu-latest
          - triple: x86_64-pc-windows-msvc
            runner: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref || github.sha }}
          fetch-depth: 0

      - name: Set up pixi env (linux)
        if: ${{ runner.os != 'Windows' }}
        uses: ./.github/actions/setup-env
        with:
          environments: dev
          cache-write: false

      - name: Set up Rust (windows)
        if: ${{ runner.os == 'Windows' }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Echo
        shell: bash
        run: |
          echo "Building ${{ matrix.triple }} on ${{ runner.os }}"
